from pipeline_entities.pipeline.component_entities.default_component_types.plot_component import PlotComponent

from pipeline_entities.pipeline.component_entities.pipeline_component.pipeline_component_decorator import pipeline_component
from pipeline_entities.pipeline.component_entities.component_meta_info.defaults.plot_components.old_interpolants_plot_component_meta_info import old_interpolants_plot_component_meta_info

from utils.old_interpolants_plot_component_utils import OldInterpolantsPlotComponentUtils
from constants.internal_logic_constants import OldInterpolantsPlotComponentConstants


@pipeline_component(id="old interpolant plotter", type=PlotComponent, meta_info=old_interpolants_plot_component_meta_info)
class OldInterpolantsPlotComponent(PlotComponent):
    PLOT_COMPONENT_UTILS_CLASS = OldInterpolantsPlotComponentUtils
    PLOT_COMPONENT_CONSTANTS_CLASS = OldInterpolantsPlotComponentConstants
