name: Python Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests recursively
        env:
          PYTHONPATH: ${{ github.workspace }}/internal_project
        run: |
          # rekursiv alle Test-Dateien finden und unittest für jede ausführen
          find internal_project/tests -name "*.py" | while read test_file; do
            echo "Running $test_file"
            python -m unittest "$test_file"
          done
