#name: Python Tests
#
#on:
#  pull_request:
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Set up Python 3.13
#        uses: actions/setup-python@v4
#        with:
#          python-version: 3.13
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#
#      - name: Run tests for CLI project
#        env:
#          PYTHONPATH: ${{ github.workspace }}/cli_project
#        run: |
#          set +e  # Fehler sollen die Schleife nicht abbrechen
#          FAILED_TESTS=()
#
#          for test_file in $(find cli_project/tests -name "*.py"); do
#            echo "Running $test_file"
#            python -m unittest "$test_file"
#            if [ $? -ne 0 ]; then
#              FAILED_TESTS+=("$test_file")
#            fi
#          done
#
#          echo ""
#          if [ ${#FAILED_TESTS[@]} -ne 0 ]; then
#            echo "==== Failed Tests ===="
#            for test in "${FAILED_TESTS[@]}"; do
#              echo "$test"
#            done
#            exit 1
#          else
#            echo "All tests passed!"
#          fi

#name: Python Tests (CLI project)
#
#on:
#  pull_request:
#
#jobs:
#  cache-dependencies:
#    runs-on: ubuntu-latest
#    outputs:
#      cache-hit: ${{ steps.cache-python-deps.outputs.cache-hit }}
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Set up Python 3.13
#        uses: actions/setup-python@v4
#        with:
#          python-version: 3.13
#
#      - name: Cache Python dependencies
#        id: cache-python-deps
#        uses: actions/cache@v3
#        with:
#          path: ~/.cache/pip
#          key: python-deps-${{ hashFiles('requirements.txt') }}
#          restore-keys: |
#            python-deps-
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#
#  test:
#    runs-on: ubuntu-latest
#    needs: cache-dependencies
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Set up Python 3.13
#        uses: actions/setup-python@v4
#        with:
#          python-version: 3.13
#
#      - name: Restore Python dependencies cache
#        uses: actions/cache@v3
#        with:
#          path: ~/.cache/pip
#          key: python-deps-${{ hashFiles('requirements.txt') }}
#          restore-keys: |
#            python-deps-
#
#      - name: Install dependencies (if needed)
#        run: |
#          python -m pip install --upgrade pip
#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#
#      - name: Run tests for CLI project
#        env:
#          PYTHONPATH: ${{ github.workspace }}/cli_project
#        run: |
#          set +e
#          FAILED_TESTS=()
#
#          for test_file in $(find cli_project/tests -name "*.py"); do
#            echo "Running $test_file"
#            python -m unittest "$test_file"
#            if [ $? -ne 0 ]; then
#              FAILED_TESTS+=("$test_file")
#            fi
#          done
#
#          echo ""
#          if [ ${#FAILED_TESTS[@]} -ne 0 ]; then
#            echo "==== Failed Tests ===="
#            for test in "${FAILED_TESTS[@]}"; do
#              echo "$test"
#            done
#            exit 1
#          else
#            echo "All tests passed!"
#          fi

name: Python Tests (CLI project)

on:
  pull_request:

jobs:
  caching-job:
    runs-on: ubuntu-latest
    outputs:
      venv-path: ${{ steps.set-venv.outputs.path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Create virtual environment
        id: set-venv
        run: |
          python -m venv .venv
          echo "::set-output name=path::.venv"

      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            venv-

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  test-job-cli:
    runs-on: ubuntu-latest
    needs: caching-job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Restore virtual environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            venv-

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/cli_project
        run: |
          source .venv/bin/activate
          set +e
          FAILED_TESTS=()
          for test_file in $(find cli_project/tests -name "*.py"); do
            echo "Running $test_file"
            python -m unittest "$test_file"
            if [ $? -ne 0 ]; then
              FAILED_TESTS+=("$test_file")
            fi
          done
          if [ ${#FAILED_TESTS[@]} -ne 0 ]; then
            echo "==== Failed Tests ===="
            for test in "${FAILED_TESTS[@]}"; do
              echo "$test"
            done
            exit 1
          else
            echo "All tests passed!"
          fi

  test-job-internal_logic:
    runs-on: ubuntu-latest
    needs: caching-job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Restore virtual environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            venv-

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/internal_project
        run: |
          source .venv/bin/activate
          set +e
          FAILED_TESTS=()
          for test_file in $(find internal_project/tests -name "*.py"); do
            echo "Running $test_file"
            python -m unittest "$test_file"
            if [ $? -ne 0 ]; then
              FAILED_TESTS+=("$test_file")
            fi
          done
          if [ ${#FAILED_TESTS[@]} -ne 0 ]; then
            echo "==== Failed Tests ===="
            for test in "${FAILED_TESTS[@]}"; do
              echo "$test"
            done
            exit 1
          else
            echo "All tests passed!"
          fi
